name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build .

      - name: Download & install minio client
        run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc \
          --create-dirs \
          -o ~/minio-binaries/mc

          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/

          mc --help

