name: Go
on: [push]
jobs:

  build:
    name: Convert CSV to Parquet
    runs-on: ubuntu-latest
    steps:

      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build converter
        run: go build . -o ./bcecsv2export

      - name: Download & install minio client
        env:
          BCE_ENDPOINT: ${{ secrets.BCE_ENDPOINT }}
          BCE_ACCESS_KEY: ${{ secrets.BCE_ACCESS_KEY }}
          BCE_PASSWORD: ${{ secrets.BCE_PASSWORD }}
        run: |
          ./bcecsv2export --output test.parquet
          ls -al test.parquet

